package com.middleware.server.mapper;

import com.middleware.server.model.PO.PrivilegePO;
import com.middleware.server.model.PO.PrivilegePOExample;
import java.util.List;

public interface PrivilegePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int insert(PrivilegePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int insertSelective(PrivilegePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    List<PrivilegePO> selectByExample(PrivilegePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    PrivilegePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PrivilegePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PrivilegePO record);
}