package com.middleware.server.mapper;

import com.middleware.server.model.PO.RolePrivilegePO;
import com.middleware.server.model.PO.RolePrivilegePOExample;
import java.util.List;

public interface RolePrivilegePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int insert(RolePrivilegePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int insertSelective(RolePrivilegePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    List<RolePrivilegePO> selectByExample(RolePrivilegePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    RolePrivilegePO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RolePrivilegePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_privilege
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RolePrivilegePO record);
}